apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth0-sso-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hoangbaoan1901/information-system_UET.git
    targetRevision: master
    path: sem6/ent_app/auth0_sso/k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true