apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-k8s-app-container
          image: springio/gs-spring-boot-docker:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000