apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth0-sso-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth0-sso
  template:
    metadata:
      labels:
        app: auth0-sso
    spec:
      containers:
        - name: auth0-sso
          image: hoangbaoan1901/auth0_sso:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"