apiVersion: v1
kind: Service
metadata:
  name: auth0-sso-svc
spec:
  selector:
    app: auth0-sso
  ports:
    - port: 80
      targetPort: 3000
      name: http  # Add this line - must match the port in ServiceMonitor
  type: ClusterIP